---
title: "About Me"
format: html
comments: false
---

### Basics
I am Dr. Tony Dunsworth. I have been working with data in public safety answering points _(PSAPs)_ for nearly 15 years. Over that time, I work to find new ways to use the data generated by PSAPs to help a center be better staffed, more responsive to the community, and to help the community discover issues that can be addressed to reduce calls to the center. During my tenure in public safety, I've worked as a CAD manager, DBA, Data Analyst, and a Data Scientist.

I completed my PhD work at [National University](https://nu.edu) in Data Science. Most of my research concerned both Public Safety Emergency Communications Centers _911/999/112_ systems and time series forecasting models. My [dissertation](https://www.proquest.com/openview/ae5915030ac635120b2c4a8207022e65/1?pq-origsite=gscholar&cbl=18750&diss=y) evaluated the efficacy of automated forecasting libraries like Prophet or TimeGPT in building accurate forecasts for noisy multi-stochastic datasets like Emergency Communication Center call volumes. 

## Education

National University | La Jolla, CA
PhD in Data Science | July 2021 - October 2024

Western Governors University | Salt Lake City, UT
M.S. in Data Analytics | September 2017 - May 2021

University of Phoenix | Kansas City, MO
Masters in Information Systems | February 2005 - May 2007

Western Governors University | Salt Lake City, UT
B.S in Software Development | September 2012 - June 2017

Univerity of Kansas | Lawrence, KS
B.A. in Linguistics | August 1987 - May 1991

## Experience

City of Alexandria | Database Administrator II | December 2014 - present

Johnson County Sheriff's Office | CAD Administrator | Sept 2010 - November 2014