---
title: "Getting Certified"
author: "Tony Dunsworth, Ph.D."
date: "2025-08-26"
categories: [data science, certification, studying]
execute: 
  eval: false
---

As my readers know, from following this blog, I work with [CompTIA](https://www.comptia.org/en-us/) on developing certification exams for Database Administrators and Data Analysts. One of the criteria for sunject matter experts is that we hold a valid CompTIA certification outselves. Thankfully, they were gracious enough to suspend that for me while I was finishing my Ph.D. Now that I've finished it, I know that I have to start working on obtaining a certification. At one point, I held four CompTIA certfications, but I sadly allowed them to lapse because I was working on a Masters in Data Analytics. The ones that I held were the A+, the Network+, the Security+ and the Project+ certs. I suppose that, with a little review time, I could retake the exams and obtain all four of them. However, I won't make use of them in my day job any longer, so it feels like it defeats the purpose. 

While we work on the exams, CompTIA reminds us to ensure that we focus on things that the target audience would acutally need to know or do in their daily work. I think that is an excellent idea. So, I'm going to follow the same advice for the selection of the certification I am choosing to pursue. In this case, I'm starting to study for the [DataX](https://partners.comptia.org/docs/default-source/resources/comptia-datax-dy0-001-exam-objectives-(5-0)) exam. I applied to work on this exam, but I was told that my qualifications were insufficient. At first, I was surprised because I thought that my resume was impressive enough to work on this exam. In retrospect, I can see where I fell short. While I had a lot of experience in data analytics and statistics, I wasn't working as a data scientist on a daily basis, so I was just a bit short. I might reapply after I get the certification since I think the combination of passing the exam and having the Ph.D. might qualify me. 

Until then, like anyone else, I have to study to prepare for the exam. So far, to do that, I picked up a book of questions from Amazon and have it on my Fire tablet. I know that most of the questions are not in the CompTIA format, but it's a good way to review different topics that may be covered on the exam. I've also purchased a Udemy course for the exam. I've used some of them in the past to help me study and they were effective when I made good use of them. So that's an emerging discipline issue that I will address. 

The first exam objective, according to the CompTIA document I've linked above is mathematics and statistics. It makes sense to me since math is the foundation of analytics and data science. In this section, the 