---
title: "Updated Directions"
author: "Tony Dunsworth"
date: "2025-04-10"
categories: [news, thoughts, updates]
---

It has certainly been way too long since I've written a blog post. I know that I promised myself and my readers, if I have any left, that I would do better with this, but here we are. Life has a funny way of getting in the way when you least expect it. However, those same recent events have given me considerable fodder for new posts that could be in the pipeline. 

I've been working on a few projects lately. Many of those projects are going to be the bases of many future posts. The first of those is a piece of software that I'm working on`to generate more realistic synthetic data for use in presentations and data science for public safety. The problem with the current iteration of the software is that I don't like how the distributions are appearing. I'm working on different distributions to create one that I believe will be more representative of actual centre data.

the other large project on the deck is called <ins>*It's About Time!*</ins> Time is essential in every part of any 9-1-1 service call. It starts with a time stamp at every step in the call process. The passage of time can determine a call's outcome. We can go further and ask how one event can influence another. Can the time spent at a specific point in the process tell you how likely the event will be successful? Can we see how well we meet our SLAs to partner organizations by viewing how well we handle the setup? 

In each CAD on the market, calls that have been closed can be re-opened or cloned into a new call. The preferred method is to clone the call to preserve the timestamps in the original call. When a call is re-opened, some of the timestamps associated with it will change. This can create very large values and can create negative values when subsequent events seem to occur prior to the prior values. Both of these situations can throw off a centre's statistics and alter the perception of how it performs. Now that those skewed values are in place after a re-opened call, subsequent analysis must employ amelioration techniques to address those outlying values.

I am also involved in a group that is looking to build a new staffing recommendations model for 9-1-1 centres. The organisation with which I volunteer, [NENA](https://www.nena.org), is looking to replace a 20+ year old study of staffing models with something that is balanced, appropriate for PSAPs of all sizes and call volumes. We also want to look at other factors that can identify good dispatchers and then find better ways to keep them. 

I have been working, for some time, on creating a new series of reports for the centre I work in. However, I think I want to extend that another level. I think that I would like to create software that would allow a centre to select a csv file, pass it like a parameter to the software and get an analysis in return. I think that I would want to make a stand-alone version and a cloud version. The cloud version would be less expensive in return for use of the data, after anonymization, for additional research projects. I will start building my lists of must-have, want-to-haves, and would-be-nice-to-haves. From there, I will design everything from the ground up and then we will see where it goes from there. 

So, dear readers, if you have any comments, questions, thoughts, or cards to the players; feel free to let me know. I would like to hear from you and see where we can go next. 