---
title: "So where does the data take me?"
author: "Tony Dunsworth"
date: "2025-01-18"
categories: [news, editorial, data science]
---
# Reflections about the last week

I just finished a week at [NENA's](https://nena.org) Standard and Best Practices. I had a wonderful time with my presentations on developing staffing models, data management, and using data better in call processing. I met a lot of new friends and I see a lot of opportunities ahead of me to make a real difference at the intersection of public safety and data science.

This is, however, where I'm going to get on my soapbox and address something I am hearing more and more of, not only in the  centres, but in civic government as well. I admit that I have phrases and words that I don't like and that I will not use or accept from others when we're working on projects. In statistics, I hate the word *average*. It's meaningless. Define which measure of central tendency you mean and stick with it. If the distribution is normally distributed, then stick with the mean and call it such. If it's not, then choose either the median or the mode. I prefer the median myself, but don't use **average**.

When it comes to Analytics, I hate hearing anyone say *Trust Me*. No! We should ***never*** tell our clients to trust us. We have to earn that trust and prove what we are saying and that our analyses are valid. Just no. We don't demand trust, we require proof.

In this conference, however, I found my biggest pet peeve becoming a central focus of the week. That phrase is *data-driven decision making*. Granted, anything *"data driven"* is just as annoying. I have a couple of different objections to the phrase. The first is, why are you letting the raw product, data, drive you anywhere? You should be applying context to the data to create information and then acting on the information. Once you act on the information and have your results, you've created intelligence and that drives innovation and better decision making. The data doesn't do it. The intelligence you derive from the data does. So, let's stop with the nonsense and focus on decision making from actionable intelligence which comes after analysis and context are added to data to derive its true value.

Additionally, if you claim you're data-driven in your decision making, where is the data? Do you know what data you need for the decision? Where is it located? What transformations need to be applied to it to make it meaningful information? I'm not suggesting that you have to be a data scientist or know where every piece of data is in order to make any decision. Rather, what decision do you need to make? What data sources need to be accessed to inform the decision? What specific data do you need in those sources? There are many other questions to ask in my opinion. However, the gist of everything I'm saying is that you need to know what data you need? Know how to access it to create the information needed for the decision. Yes, the access method can be directing someone else to access the data, harvest it, clean it, and present it back to you in a form to inform your decision. These methods become information-driven decision making or information-driven intelligence creation. Eother way, it's more than a simpole dataset.

Now that the early portion is out of the way, if you think about it, saying you're *data-driven* isn't really saying anything at all. All of our decisions, even *gut instinct* has some data behind it. I think that the buzz-phrase is simply trying to assert that decision makers are looking at some form of external data source to justify their decisions. The problem with this is, you're not using raw data to make decisions. You do have to contextualize it somehow. So it's not raw data any longer. Instead it's now information-based. It is data in context. So it's information.

When I am working with the decision makers in my centre, I start out by playing my version of 20 questions. The point of that is to determine exactly what data is needed to address the request. After everyone is clear on the data that is needed, I harvest it, clean it, and prepare it. Obviously part of that preparation is data analysis that focueses on the question asked.

## NENA's SBP

I participated in seven presentations. I will upload slide decks and notes later for people who are interested in learning what I was talking about in detail. Three of these were in a block discussing the need for a new staffing model recommendation in 911 centres. Currently, NENA's [Staffing Recommendations](https://cdn.ymaws.com/www.nena.org/resource/resmgr/standards/NENA-REF-001-2003_PSAP_Staff.pdf) are over 21 years old and rely heavily on the [Erlang-C](https://myweb.ecu.edu/robbinst/PDFs/Erlang%20Compare%20Working%20paper.pdf) model for staffing recommendations. There has been a tonne of work in queuing theory since the development of this formula. And, as referenced in the linked paper, there are legitimate questions about how appropriate the Erlang model family is for regular call centres, let alone 911 centres.

Two of the other presentations centered around the [Emergency Incident Data Object](https://cdn.ymaws.com/www.nena.org/resource/resmgr/standards/NENA-STA-021.1b-2021_2024121.pdf). This is how, we propose, to move information between different systems and entities in public safety. It's in a JSON object that leverages [NIEM](https://www.niem.gov/) to define the objects passed between entities. My presentations dicussed the JSON object itself and the conveyance mechanisms by which the JSON objects are moved between entities.

The other presentations in which I participated were the Call Processing working group where I am the *'data SME'* and the [Future Think](https://www.nena.org/page/standards#FutureThink) committee's Data Management and Presetation work. That was a fun panel discussion with a lot of great audience participation.

I am heartened, as a data scientist working in public safety, to hear my colleagues in public safety acknowledging the need to use data analytics, regression modeling, predictive analytics, and forecasting to improve things for telecommunicators. 