---
title: "Building a new reporting system"
author: "Tony Dunsworth, Ph.D."
date: "2025-08-10"
categories: [development, software]
execute: 
  eval: false
---

I have a lot of projects in the works, probably too many to be honest. However, at the day job, the one that has been bouncing around the longest and is now the centre of my attention is building an updated reporting structure. Currently, most of the regular reports that I generate are call lists that fit certain criteria. This has satisfied management at multiple levels for a while now, however, I haven't been satisfied with it. I have wanted to change things up and bring more data into the reports. I've also wanted to expand the comparative statistics to determine where, if at all, correlations exist in operations. It is also, in my opinion, good to discern any trneds that could be present in the data. Something call lists may miss.

The whole project will be deployed in five phases. The first phase is building the infrastructure. I know that may sound boring, but my experiences in engineering and analytics is that most of the job is boring to most people. I don't mind it at all, so I'm happy to take my time. The first decision is that of programming language. While I, typically, prefer R over Python, in this instance, I'm reversing that decision because I believe that I can accomplish the other phases more efficiently code-wise in Python. I would like to try this in R as well, but that is a project for another day. When this is done perhaps.

