---
title: "NENA 25 National Convention - Long Beach"
author: "Tony Dunsworth, Ph.D."
date: "2025-07-04"
categories: [updates, news]
execute: 
  eval: false
---

Once again, I haven't written in a long time. I know *Bad Dr. D*! I have not been as diligent as a blogger as I would like to be. So now that my mea culpa is out of the way, let's proceed to the next step in this blog, actually discussing information.

Last week, I was out in Long Beach, CA at the [NENA](https://nena.org) 2025 Annual Convention at the Long Beach Convention Center. It was a bit of an "old home" week for me. I used to live near the convention center over 20 years ago. Obviously, some things were completely differnt while some things have not changed. In a way, it was nice to be back in the area. I was able to take the old Green Line and the Blue Line to get down to Long Beach from the airport. 

However, once the convention started, I found myself a lot busier than I expected I would be. I had two presentations to give. 