---
title: "Building a data-centric future"
author: "Tony Dunsworth, Ph.D."
date: "2025-08-19"
categories: [research. data-driven, data]
execute: 
  eval: false
---

As most of you know, I have a few outside activities where I can use my skills to better things around me. For example, I contribute to first-look book reviews for [Manning Press](https://www.manning.com/). I am a subject matter expert for [CompTIA](https://www.comptia.com/) on a couple of different exams. I also volunteer my time and energy for [NENA](https://www.nena.org/), the National Emergency Number Association. I work on standards and best practice development there. Recently, at their annual convention in Long Beach, CA., I had an idea to suggest something new. The new [NENA board](https://www.nena.org/page/board) president, Lee Ann Magoski, challenged all of us in her inauguration speech to use more of the data we generate and use it more effectively. I started thinking about submitting a form to create a working group that could assist in completing data collection and analysis for other working groups that need it to further their work on standards and best practices. I ran my idea past some colleagues and I was pleasantly surprised to hear a lot of support. That support extended to colleagues offering their advice and support to help me with the paperwork and ensure that the community can be built and sustained. 

Not long after I returned home from the convention, I spoke with others