---
title: "Stochasticity in Time-Series, Dissertation part 1"
author: "Tony Dunsworth, Ph.D."
date: "2025-09-18"
categories: [data science, analyses, data issues]
execute: 
  eval: false
---

## Background

It's been nearly a year since I defended my dissertation. In that time, I've found that people are intrested in knowing what it's about until I try to explain it, then they feel that they don't understand it and the discussions get lost. So, while I was playing FreeCell solitaire this morning, I thought of an experiment that could help me work with forecasting stochastic processes, including adding conformal predictions to the mixture. Part of it is because I want to keep my data science skills sharp. I also realized that this would work well as a better explanation of my dissertation also. So my plan is to split everything into three parts. This part is going to discuss stochasticity and how it plays a part of forecasting. The second part will be focused low-code and zero-shot forecasting models. The final part will be marrying these together, like I did in my dissertation, for 9-1-1 centres and how my dissertation can serve as a foundation for future research on both forecasting polystochastic processes and finding even better ways to address forecasting in centers and why it will be important.

### Simple Stochasticity

This all started with a weird thought playing FreeCell. When I started playing, years ago, I was happy anytime that I had scores under 100 moves. Now, the more I've played and improved, I am annoyed whenever I have a count above 90. That certainly is a big difference. It made me wonder, had I thought of it earlier, could I have built a dataset that charted my progress and then forecast things such as which days are going to be more challenging?

Ultimately, this is a simple stochastic process. The "mother-ship" selects a deal at random each day. There are a finite number of choices, according to a quick search, there are $1.75^{64}$ possibilities. The program, as part of the trivia, points out that some deals are unwinnable. So the rules that the "mother-ship" must follow also includes, for the daily challenges, the exclusion of unwinnable deals. The program also attaches the daily deal number to the day it is presented, so even if I don't complete the daily deal, I'm guaranteed to see the same daily deal that my wife or other players saw the same day. This introduces the stochastic element through the determination of limiting factors. If the daily deal were truly random, then unwinnable deals would be possible and the deal offered would change when presented to the player depending on when it was accessed.

My analytical interest, had I started earlier would be to use my prior results to see how my play has improved over time and see if I can forecast how well I can do in the future. I also am curious to see if there is an underlying pattern of when really challenging deals are presented to players. I could correlate my wife's results with mine to see if a second pattern emerges. This yields the possibility of two separate types of stochastic forecasts. It also allows me to create pattern recognition analyses that may shed some insight into the algorithm the company employs to select the deal for each day. Is it simply a random number generator with some values removed? Or are there other parameters that are added which restrict the lists enough to ensure a player doesn't perceive repeated deals or perhaps you can ascertain the size of the potential pool of deals.

### Double Stochasticity

This is most generally found in many commercial call centres. Most accurately, a [Cox Process](https://www.sciencedirect.com/topics/mathematics/cox-process) is not only doubly stochastic, but it also follows a Poisson distribution, mathematically. The best illustration is if we lived in the same area together and the cable or internet service goes out. The cable company's customer service center will receive a random number of calls per hour. Usually, during operating hours, I would posit that it should be a non-zero, non-negative integer, but for our purposes, it will be zero or larger at each time interval. That is the first stochastic element.