---
title: "How to Start - Asking the First Question (Python Version)"
author: "Tony Dunsworth, Ph.D."
date: "2025-04-20"
categories: [examples, analyses]
execute: 
  eval: false
---

## Why am I doing this again?

After I published the [R langauage](https://www.r-project.org/) version of this the other day, I realized that not all of my audience is going to be as happy or comfortable with the R language as I am, so in an effort to address that, I thought that I would sort-of repeat myself using [Python](https://www.python.org/). This is the first time that I'm presenting Python code on this site, but I don't believe it will be the last. 

### Before we start the flame wars.....

In my case, I started with R first. Over 15 years ago, when I was working as a back-end web developer, I wanted to find free resources to improve my skills and my knowledge. At the time, [O'Reilly Media](https://www.oreilly.com/) offered a reviewer program where you could get a book for free if you were willing to write a review of it on your blog. That's what also started my first Amazon account, by the way. One of the first books that I reviewed was [<ins>Learning R</ins>](https://www.oreilly.com/library/view/learning-r/9781449357160/?_gl=1*x65p3g*_ga*MTc3MzQzMTQzMS4xNzQ0OTk3ODU0*_ga_092EL089CH*MTc0NDk5Nzg1NC4xLjEuMTc0NDk5ODAwNC4yNi4wLjA.) by Richard Cotton. I found it very interesting and engaging. Because of that I started on the R side of the fence and I default there most of the time. 

During my Ph.D. dissertation, I found that many of the forecasting libraries I wanted to use had more features in, or were only written for Python. So I brought myself up to speed on Python in a hurry. I have found that both languages can do all of the basics quite well, but when I'm doing more advanced programming with neural networks and 