---
title: "Update and Silence Explanation"
author: "Tony Dunsworth, Ph.D."
date: "2026-01-15"
categories: [data science, analyses, hosting, thoughts]
execute: 
  eval: false
---

## It's been a while

I apologize to the people that read this. I have been working to find a new host for the site. I finally found one, uploaded everything and had to wait for it to settle out so it's live again. I know that it's obvious that the site is up because you're reading this. So, what have I been doing in the meanwhile? I'm still plugging away at the new reporting system. I've done all of it in R at this point and will transfer it over to Python later. It took me quite a bit of coding work to get everything in a new forecasting section to work properly in R code. The goal is to take the last 5 weeks that are available to the engine and forecast the number of calls on the 9-1-1 and the non-emergency lines, and the number of CAD service events created for the week. Right now, I've been experimenting with both daily and weekly forecasts. For the experiment with forecasting, I'm leveraging the [fable](https://fable.tidyverts.org/) package.

I've been studying for CompTIA's [DataX](https://www.comptia.org/en-us/certifications/datax/) certification. I have to get a CompTIA certification eventually, so this one makes the most sense for me. I'm taking a Udemy course for it and I have to laugh. My wife is convinced that the training is for someone who has never seen data before. I have to say that I can't disagree. I'm hoping that the courses focus on more challenging topics soon. I paid for it, so I will continue the course. I think that I will do pretty well with it.

Tonight *2026-01-12*, I'm sitting in New Orleans at [NENA's](https://www.nena.org) Standards and Best Practices (SBP) conference. I spoke in two presentations today. I will help give a presentation tomorrow, the 13th, and I will have another one on Wednesday the 14th. Two of the presentations cover a data survey we've developed in the working groups to gather data for each of the repsective standards. The working model of the survey is [here](https://drddatascience.com/survey). We are hoping to gather data to make standards and recommendations that are scientifically valid. That way we can fulfill our duty to ANSI as a standards body and we can ensure that our work can withstand scrutiny. This won't be the final host for the site. It's here, now, to give people a chance to view it and make comments. When it is ready to host, NENA will control the space, the code, and the data that we collect. We also want to ensure the anonymity of the survey participants because we do not want them to feel uncomfortable sharing data. There will be no judgement for what the numbers look like. We just want to have the numbers to advance our work.

The funny part is that part of tomorrow's presentation will cover much of the same topics, especially with the survey, that we covered today, just flavored with a different angle. The need for the data is no different. I am really looking forward to trying something different when it comes to the workshop on Wednesday. I wanted only a few slides so we can link things together, then I want to wade into the crowd, literally, to see what problems we can solve in the real world.

So, I will take some more notes to update the site and see what else we can do. I will start writing more frequently again.